backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections:
  - name: "questions"
    label: "Game Questions"
    folder: "content/questions"
    create: true
    format: "json"
    slug: "{{id}}"
    fields:
      - {label: "Puzzle Number (ID)", name: "id", widget: "number", required: true, min: 1, value_type: "int", step: 1, hint: "Enter a unique number for each puzzle. This will be used as the filename."}
      - {label: "Prompt Part 1 (Before Undivided)", name: "promptPart1", widget: "markdown", required: true, hint: "Text before the main undivided word. Use *asterisks* for italics, **double asterisks** for bold."}
      - {label: "Undivided Word (for Hints)", name: "undividedWord", widget: "string", pattern: ["^[a-zA-Z]+$", "Only letters allowed, no spaces."], required: true, hint: "The full word before division, e.g., 'disconsolate'"}
      - {label: "Prompt Part 2 (Before Divided Word 1)", name: "promptPart2", widget: "markdown", required: true, hint: "Text before the first divided word."}
      - {label: "Divided Word 1", name: "dividedWord1", widget: "string", pattern: ["^[a-zA-Z]+$", "Only letters allowed, no spaces."], required: true, hint: "First part of the divided word (e.g., 'disc')."}
      - {label: "Prompt Part 3 (Before Divided Word 2)", name: "promptPart3", widget: "markdown", required: false, hint: "Text before the second divided word. Optional."}
      - {label: "Divided Word 2", name: "dividedWord2", widget: "string", pattern: ["^[a-zA-Z]+$", "Only letters allowed, no spaces."], required: false, hint: "Second part of the divided word (e.g., 'on')."}
      - {label: "Prompt Part 4 (Before Divided Word 3)", name: "promptPart4", widget: "markdown", required: false, hint: "Text before the third divided word. Optional."}
      - {label: "Divided Word 3", name: "dividedWord3", widget: "string", pattern: ["^[a-zA-Z]+$", "Only letters allowed, no spaces."], required: false, hint: "Third part of the divided word (e.g., 'so')."}
      - {label: "Prompt Part 5 (Before Divided Word 4)", name: "promptPart5", widget: "markdown", required: false, hint: "Text before the fourth divided word. Optional."}
      - {label: "Divided Word 4", name: "dividedWord4", widget: "string", pattern: ["^[a-zA-Z]+$", "Only letters allowed, no spaces."], required: false, hint: "Fourth part of the divided word (e.g., 'late')."}
      - {label: "Prompt Part 6 (After All Blanks)", name: "promptPart6", widget: "markdown", required: false, hint: "Any text after the last blank. Optional."}